# General Jekyll Config
highlighter: rouge

author: Jaan Janesmae
tagline: "This is probably not the Jaan you are looking for. Move along!"
email: jaan@janesmae.com

url: http://jaan.janesmae.com
permalink: /posts/:year/:month/:title.html
relative_permalinks: false

lsi: false
branch: master

gems:
  - jekyll-sitemap
  - jekyll-feed

github:
  repository_nwo: "janesmae/janesmae.github.io"
  owner_url: "https://github.com/janesmae"
  owner: "janesmae"
  repository_url: "https://github.com/janesmae/janesmae.github.io"

# Google Analytics key, leave blank to ignore
google_analytics: UA-36904074-1

exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
